### PR TITLE
multi graph

### PR DESCRIPTION
**Pull request by avibryant**

### CODE REVIEW

**Comment by avibryant** [comment]
A few high-level questions/concerns before doing any detailed feedback in the code. I'll break them up into separate comments for ease of replying.

If mutating the parameters in a `ComputeState` is going to reset the cache for everything else, why not just construct a new `ComputeState`? Relatedly, I don't see that we will ever change just a single parameter at a time; we should always be providing an entirely new set of parameters at once.

**Comment by avibryant** [comment]
(minor) are we planning to have multiple implementations of `ComputeState`? If not I'd rather just have `ComputeState` as a concrete class (or an ADT-style `interface` with associated functions)

**Comment by avibryant** [comment]
right now it's cool to have `optimize` as a generator because we want to animate every iteration but pretty soon that will only be interesting as a debug mode, and the vast majority of the time we will want the optimizer to go to completion inside WASM. Since we probably won't expose a generator API from WASM I think it might be better to stay away from it

**Comment by pdubroy** [comment]
> If mutating the parameters in a ComputeState is going to reset the cache for everything else, why not just construct a new ComputeState?

In the JS/TS version that would make sense. The interface was more driven by my assumption that in the Wasm implementation, we want to avoid dynamic allocation and just update the cache in place. Does that make sense

> Relatedly, I don't see that we will ever change just a single parameter at a time; we should always be providing an entirely new set of parameters at once.

Makes sense, I can update the API to only support that case.

**Comment by pdubroy** [comment]
> Do we even need a stateful `Evaluator` object? Separating out the idea of a `ComputeState` makes sense to me but at that point we could just have `function evaluate(num: Num, state: ComputeState): double`. I don't see any benefit (and I do see some drawbacks) of having the stateful `Evaluator` wrapper.

Yeah, that was my first instinct as well (since it's what you described in the PROBPROG paper) and the initial version did just that. But, the Wasm implementation currently uses globals, so for now I went with the interface that wouldn't force me to change that (yet).

But, I just realized that I can't easily update params when they are in globals, because the `global.set` instruction only accepts an immediate (i.e., static) argument.

So yeah, I think it makes sense to make the evaluator itself stateless. It should be possible to implement a `WasmComputeState` with a `WebAssembly.Memory` object.

**Comment by pdubroy** [comment]
> (minor) are we planning to have multiple implementations of `ComputeState`? If not I'd rather just have `ComputeState` as a concrete class (or an ADT-style `interface` with associated functions)
> 
> _edit: actually never mind about `interface`, I think it's useful to have it as a `class` as a marker of mutability_

The plan was to have a `WasmComputeState` too. But you're right, we wouldn't actually need both implementations — the Wasm one should be usable from TS too.

**Comment by pdubroy** [comment]
> right now it's cool to have `optimize` as a generator because we want to animate every iteration but pretty soon that will only be interesting as a debug mode, and the vast majority of the time we will want the optimizer to go to completion inside WASM. Since we probably won't expose a generator API from WASM I think it might be better to stay away from it

Good point.

**Comment by avibryant** [comment]
See https://github.com/avibryant/kombu/wiki/Computation-Lifecycle for some context that should influence these APIs. The two big takeaways for me are a) the compiled optimizer and interpreted evaluator are very different things, and unifying their APIs (or their caching APIs) seems bad because of that, and b) it *would* be very nice to be able to feed the optimizer's cache into the evaluator's cache as an initialization step (but not vice versa).

**Comment by pdubroy** [comment]
Superceded by #3

**Pull request closed without merging**
